defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: step_{step:03d}_loss{val/loss:.3f}
  monitor: ${monitor}
  verbose: False
  save_last: True
  save_top_k: 2
  mode: 'min'
  auto_insert_metric_name: False
  save_weights_only: False
  every_n_train_steps: ${ckpt_interval}  
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null

early_stopping:
  monitor: ${monitor}
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1

learning_rate_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: ${OptimizerInterval}
